syntax enable
set nocompatible
set showmode
set showcmd
set number
set ruler
set hlsearch
set background=dark
set backspace=indent,eol,start
set encoding=utf-8
set scrolloff=5
set sidescrolloff=15
set showmatch
set autoindent
set mouse=a
set noexpandtab
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set noeb
set vb
